site_name: TacticalGaming ARMA - Loadouts
site_description: Loadouts for the TacticalGaming ARMA Division.
site_author: TGxSilK
site_url: https://tacticalgaming-net.github.io/arma-loadouts/

nav:
- Echo 1-2: loadouts/echo.md

markdown_extensions:
- pymdownx.details
- pymdownx.superfences

theme:
  name: material
  
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  
  include_homepage_in_sidebar: false